# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1279, 852))
        self.graphicsView.setStyleSheet("border-image: url(:/main_page_pic/C:/Users/Dell/Downloads/Simple Login Page Website Desktop Prototype.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.label_options = QtWidgets.QLabel(self.centralwidget)
        self.label_options.setGeometry(QtCore.QRect(20, 10, 131, 41))
        self.label_options.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    color: white; /* Hoặc màu chữ tùy chỉnh */\n"
"}")
        self.label_options.setObjectName("label_options")
        self.label_price_chart = QtWidgets.QLabel(self.centralwidget)
        self.label_price_chart.setGeometry(QtCore.QRect(30, 430, 181, 41))
        self.label_price_chart.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"QLabel {\n"
"    color: white;\n"
"    background-color: transparent; /* Hoặc đặt màu nền khác nếu cần */\n"
"}")
        self.label_price_chart.setObjectName("label_price_chart")
        self.label_technicals = QtWidgets.QLabel(self.centralwidget)
        self.label_technicals.setGeometry(QtCore.QRect(20, 120, 171, 41))
        self.label_technicals.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_technicals.setObjectName("label_technicals")
        self.comboBox_num_rows = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_num_rows.setGeometry(QtCore.QRect(348, 450, 105, 28))
        self.comboBox_num_rows.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox_num_rows.setObjectName("comboBox_num_rows")
        self.label_num_rows = QtWidgets.QLabel(self.centralwidget)
        self.label_num_rows.setGeometry(QtCore.QRect(220, 450, 121, 28))
        self.label_num_rows.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_num_rows.setObjectName("label_num_rows")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 630, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_select_currency = QtWidgets.QLabel(self.layoutWidget)
        self.label_select_currency.setMinimumSize(QtCore.QSize(15, 15))
        self.label_select_currency.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_select_currency.setObjectName("label_select_currency")
        self.horizontalLayout.addWidget(self.label_select_currency)
        self.comboBox_select_currency = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_select_currency.setMinimumSize(QtCore.QSize(15, 15))
        self.comboBox_select_currency.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox_select_currency.setObjectName("comboBox_select_currency")
        self.comboBox_select_currency.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_select_currency)
        self.label_select_granularity = QtWidgets.QLabel(self.layoutWidget)
        self.label_select_granularity.setMinimumSize(QtCore.QSize(15, 15))
        self.label_select_granularity.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_select_granularity.setObjectName("label_select_granularity")
        self.horizontalLayout.addWidget(self.label_select_granularity)
        self.comboBox_select_granularity = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_select_granularity.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox_select_granularity.setObjectName("comboBox_select_granularity")
        self.horizontalLayout.addWidget(self.comboBox_select_granularity)
        self.pushButton_load = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_load.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 490, 1151, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 170, 1151, 241))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView.raise_()
        self.layoutWidget.raise_()
        self.label_options.raise_()
        self.label_price_chart.raise_()
        self.label_technicals.raise_()
        self.comboBox_num_rows.raise_()
        self.label_num_rows.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1230, 26))
        self.menubar.setObjectName("menubar")
        self.menuDashBoard = QtWidgets.QMenu(self.menubar)
        self.menuDashBoard.setObjectName("menuDashBoard")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuDashBoard.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forex Dash"))
        self.label_options.setText(_translate("MainWindow", "Options"))
        self.label_price_chart.setText(_translate("MainWindow", "Price Chart"))
        self.label_technicals.setText(_translate("MainWindow", "Technicals"))
        self.label_num_rows.setText(_translate("MainWindow", "Num. Rows."))
        self.label_select_currency.setText(_translate("MainWindow", "Select Currency"))
        self.comboBox_select_currency.setItemText(0, _translate("MainWindow", "Euro"))
        self.label_select_granularity.setText(_translate("MainWindow", "Select Granularity"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.menuDashBoard.setTitle(_translate("MainWindow", "DashBoard"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))


import main_page_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
