# Form implementation generated from reading ui file 'E:\Project\ML-final\UI\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1226, 846)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1279, 852))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:\\Project\\ML-final\\UI\\../Images/Background.png"))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 70, 630, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_select_currency = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_select_currency.setMinimumSize(QtCore.QSize(15, 15))
        self.label_select_currency.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_select_currency.setObjectName("label_select_currency")
        self.horizontalLayout.addWidget(self.label_select_currency)
        self.comboBox_select_currency = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox_select_currency.setMinimumSize(QtCore.QSize(15, 15))
        self.comboBox_select_currency.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox_select_currency.setCurrentText("")
        self.comboBox_select_currency.setObjectName("comboBox_select_currency")
        self.horizontalLayout.addWidget(self.comboBox_select_currency)
        self.label_select_granularity = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_select_granularity.setMinimumSize(QtCore.QSize(15, 15))
        self.label_select_granularity.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_select_granularity.setObjectName("label_select_granularity")
        self.horizontalLayout.addWidget(self.label_select_granularity)
        self.comboBox_select_granularity = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox_select_granularity.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.comboBox_select_granularity.setObjectName("comboBox_select_granularity")
        self.horizontalLayout.addWidget(self.comboBox_select_granularity)
        self.pushButton_load = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButton_load.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_load.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout.addWidget(self.pushButton_load)
        self.label_num_rows = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_num_rows.setGeometry(QtCore.QRect(180, 150, 91, 28))
        self.label_num_rows.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_num_rows.setObjectName("label_num_rows")
        self.label_options = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_options.setGeometry(QtCore.QRect(20, 10, 131, 41))
        self.label_options.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"QLabel {\n"
"    background-color: transparent;\n"
"    color: white; /* Hoặc màu chữ tùy chỉnh */\n"
"}")
        self.label_options.setObjectName("label_options")
        self.label_price_chart = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_price_chart.setGeometry(QtCore.QRect(20, 110, 181, 41))
        self.label_price_chart.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"QLabel {\n"
"    color: white;\n"
"    background-color: transparent; /* Hoặc đặt màu nền khác nếu cần */\n"
"}")
        self.label_price_chart.setObjectName("label_price_chart")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 210, 1151, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_num_rows_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_num_rows_2.setGeometry(QtCore.QRect(480, 150, 81, 28))
        self.label_num_rows_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_num_rows_2.setObjectName("label_num_rows_2")
        self.StartdateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.StartdateTimeEdit.setGeometry(QtCore.QRect(280, 150, 171, 22))
        self.StartdateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2024, 1, 1), QtCore.QTime(0, 0, 0)))
        self.StartdateTimeEdit.setCalendarPopup(True)
        self.StartdateTimeEdit.setObjectName("StartdateTimeEdit")
        self.EnddateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.EnddateTimeEdit.setGeometry(QtCore.QRect(570, 150, 191, 22))
        self.EnddateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2025, 3, 17), QtCore.QTime(23, 59, 59)))
        self.EnddateTimeEdit.setCalendarPopup(True)
        self.EnddateTimeEdit.setObjectName("EnddateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1226, 21))
        self.menubar.setObjectName("menubar")
        self.menuDashBoard = QtWidgets.QMenu(parent=self.menubar)
        self.menuDashBoard.setObjectName("menuDashBoard")
        self.menuHome = QtWidgets.QMenu(parent=self.menubar)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuDashBoard.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forex Dash"))
        self.label_select_currency.setText(_translate("MainWindow", "Select Currency"))
        self.label_select_granularity.setText(_translate("MainWindow", "Select Granularity"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.label_num_rows.setText(_translate("MainWindow", "Start Date"))
        self.label_options.setText(_translate("MainWindow", "Options"))
        self.label_price_chart.setText(_translate("MainWindow", "Price Chart"))
        self.label_num_rows_2.setText(_translate("MainWindow", "End Date"))
        self.StartdateTimeEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy hh:mm:ss"))
        self.EnddateTimeEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy hh:mm:ss"))
        self.menuDashBoard.setTitle(_translate("MainWindow", "DashBoard"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
