# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/SignInWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1279, 852)
        Form.setStyleSheet("")
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 1279, 852))
        self.graphicsView.setStyleSheet("border-image: url(:/Background/SignInBg.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(840, 120, 411, 161))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro Bold")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditUserNameSignIn = QtWidgets.QLineEdit(Form)
        self.lineEditUserNameSignIn.setGeometry(QtCore.QRect(760, 340, 351, 51))
        self.lineEditUserNameSignIn.setObjectName("lineEditUserNameSignIn")
        self.lineEditEmailAddress = QtWidgets.QLineEdit(Form)
        self.lineEditEmailAddress.setGeometry(QtCore.QRect(760, 430, 351, 51))
        self.lineEditEmailAddress.setObjectName("lineEditEmailAddress")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(760, 320, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(760, 410, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButtonCreateNewAccount = QtWidgets.QPushButton(Form)
        self.pushButtonCreateNewAccount.setGeometry(QtCore.QRect(760, 590, 351, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCreateNewAccount.setFont(font)
        self.pushButtonCreateNewAccount.setObjectName("pushButtonCreateNewAccount")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(770, 670, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButtonLogin = QtWidgets.QPushButton(Form)
        self.pushButtonLogin.setGeometry(QtCore.QRect(790, 670, 62, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.lineEditPassWordSignin = QtWidgets.QLineEdit(Form)
        self.lineEditPassWordSignin.setGeometry(QtCore.QRect(760, 520, 351, 51))
        self.lineEditPassWordSignin.setObjectName("lineEditPassWordSignin")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(760, 500, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Forex trading &\n"
"back testing system\n"
""))
        self.label_2.setText(_translate("Form", "User Name"))
        self.label_4.setText(_translate("Form", "Email Address"))
        self.pushButtonCreateNewAccount.setText(_translate("Form", "Create New Account"))
        self.label_5.setText(_translate("Form", "or "))
        self.pushButtonLogin.setText(_translate("Form", "Login"))
        self.label_6.setText(_translate("Form", "Password"))
import LoginWindow_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
