# Form implementation generated from reading ui file 'D:\Uni\Nam3\Ki2\MLBA\Final\ML-final\UI\SignInWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1279, 852)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1279, 752))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Uni\\Nam3\\Ki2\\MLBA\\Final\\ML-final\\UI\\../Images/SignInBg.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(760, 260, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditEmailAddress = QtWidgets.QLineEdit(parent=Form)
        self.lineEditEmailAddress.setGeometry(QtCore.QRect(760, 370, 361, 51))
        self.lineEditEmailAddress.setObjectName("lineEditEmailAddress")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(760, 610, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButtonCreateNewAccount = QtWidgets.QPushButton(parent=Form)
        self.pushButtonCreateNewAccount.setGeometry(QtCore.QRect(760, 530, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro Bold")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCreateNewAccount.setFont(font)
        self.pushButtonCreateNewAccount.setObjectName("pushButtonCreateNewAccount")
        self.lineEditUserNameSignIn = QtWidgets.QLineEdit(parent=Form)
        self.lineEditUserNameSignIn.setGeometry(QtCore.QRect(760, 280, 361, 51))
        self.lineEditUserNameSignIn.setObjectName("lineEditUserNameSignIn")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(760, 350, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditPassWordSignin = QtWidgets.QLineEdit(parent=Form)
        self.lineEditPassWordSignin.setGeometry(QtCore.QRect(760, 460, 361, 51))
        self.lineEditPassWordSignin.setObjectName("lineEditPassWordSignin")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(760, 440, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButtonLoginSignIn = QtWidgets.QPushButton(parent=Form)
        self.pushButtonLoginSignIn.setGeometry(QtCore.QRect(790, 610, 62, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLoginSignIn.setFont(font)
        self.pushButtonLoginSignIn.setObjectName("pushButtonLoginSignIn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "User Name"))
        self.label_5.setText(_translate("Form", "or "))
        self.pushButtonCreateNewAccount.setText(_translate("Form", "Create New Account"))
        self.label_4.setText(_translate("Form", "Email Address"))
        self.label_6.setText(_translate("Form", "Password"))
        self.pushButtonLoginSignIn.setText(_translate("Form", "Login"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())